version: 2
updates:
  # Maintain dependencies for our npm packages.
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      # Allow both direct and indirect updates for all packages
      - dependency-type: "all"
    commit-message:
      prefix: "Dependencies:"

  # Maintain dependencies for our github actions dependencies.
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "Dependencies:"


